name: ocr_app_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  dio: ^5.8.0+1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  flutter_dotenv: ^5.2.1
  get_it: ^8.0.3
  go_router: ^14.8.1
  google_ml_kit: ^0.19.0
  google_mlkit_text_recognition: ^0.14.0
  image_picker: ^1.1.2
  injectable: ^2.5.0

dev_dependencies:
  build_runner: ^2.4.15
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.7.0

flutter:
  uses-material-design: true
  assets:
    - .env